### PR TITLE
remove redundant public

### PR DESCRIPTION
**Pull request by Igor-Palaguta**
Fix compilation error in Xcode 10.2 as because of redundant public on func and extension

### CODE REVIEW

**Comment by tkohout** [comment]
Hey Igor, thanks for the contribution! Would you mind also updating the bin/generate script as this file is dynamically generated?

**Comment by Igor-Palaguta** [comment]
@tkohout let me check

**Comment by Igor-Palaguta** [comment]
@tkohout It would be cool if you can review this and merge with new version, if it is fine

Thanks

**Comment by tkohout** [comment]
Thanks for the contribution! I am closing this in favour of https://github.com/Swinject/SwinjectAutoregistration/pull/46 and [Release 2.6.0](https://github.com/Swinject/SwinjectAutoregistration/releases/tag/2.6.0)

**Pull request closed without merging**
