### PR TITLE
Xcode 10.2 support

### PR DESCRIPTION
**Pull request by darrarski**
This PR adds support for Xcode 10.2

### CODE REVIEW

**Comment by mpdifran** [comment]
I've opened #46 for this already.

**Comment by darrarski** [comment]
@mpdifran PR #46 is about migrating the code to Swift 5. In this PR I made minimal changes to make SwinjectAutoregistration work in Xcode 10.2. It's still Swift 4.2. I think it's a good idea to merge it and release minor version update to allow working with SwinjectAutoregistration in Xcode 10.2 as a temporary solution until it will be upgraded to Swift 5.0.

**Comment by mpdifran** [comment]
Ah sorry, just updated the title. Decided to drop Swift 5 migration and just add Xcode 10.2 support in #46. I'll open another PR for migrating to Swift 5 where we can bump the major version.

**Comment by tkohout** [comment]
Thanks for the contribution! I am closing this in favour of https://github.com/Swinject/SwinjectAutoregistration/pull/46 and [Release 2.6.0](https://github.com/Swinject/SwinjectAutoregistration/releases/tag/2.6.0)

**Pull request closed without merging**
