### PR TITLE
Changed maximum number of dependencies to 20. Optimized build times

### PR DESCRIPTION
**Pull request by tkohout**
See https://github.com/Swinject/SwinjectAutoregistration/issues/14

### CODE REVIEW

**Comment by yoichitgy** [comment]
In case of Curry, it is told that compilation performance hits over 21 generic arguments:
https://github.com/thoughtbot/Curry/commit/70f1a2b5ee18865ffdb51e658a025200600877a1

It might be good to measure the number of generic arguments to hit the compilation performance in our case.

**Comment by yoichitgy** [comment]
@tkohout, I have a question. Is it possible for a user to write `unresolvedService` and `checkResolved` for 20 arguments as a kind of an extension?

I thought it might be good to write documentation how to increase the number of arguments by users themselves. If this is possible, the compilation performance is good for users who use only limited number of arguments, and users who need more than 20 arguments can extend by themselves.

**Comment by tkohout** [comment]
Well the problem in curry is not with the number of generic arguments but the curried functions that it produces. If you write curried function with 21 non-generic arguments it won't be able to compile either.

The difference between build times of AutoRegistration with 9 and 20 dependencies is about 3s (5s vs. 8s) and that can be only result of more code that have to be compiled.

Btw I tried also create autoregistration with 50 services and it still builds in 30s so I don't think it is a big problem.

**Comment by yoichitgy** [comment]
Thanks @tkohout for the detailed info👍

I'll merge this pull request if you really want to provide 20 arguments to all the users. If you actually think 12 or 15 arguments are enough, we can reduce the number of arguments. My point is just API design.

**Comment by tkohout** [comment]
Well, I wanted to set it to a maximum number which I think will be satisfactory for all users. I just want to avoid raising it again when e.g. 12 arguments won't be enough.

**Comment by yoichitgy** [comment]
I got it👍

**Pull request merged**
