### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by jakubvano**
Updated dependencies and API to match Swinject v2 and Swift 3 guidelines

### CODE REVIEW

**Comment by tkohout** [comment]
Hello!
thanks for the pull request.

I have changed the syntax a little bit according to https://github.com/Swinject/SwinjectAutoregistration/issues/1

Can you fix the conflicts so I can merge it?

Thanks

**Comment by jakubvano** [comment]
👍 Will do, probably on Monday.

**Comment by jakubvano** [comment]
Rebased branch on current master, including syntax changes.

**Comment by jakubvano** [comment]
I have changed `assertionFailure` to `fatalError`, because former is ignored in release builds, which is problem when integrated via Carthage.

I added change to this PR for convenience - if we plan to maintain `2.x` version this should be changed there as well.

**Comment by tkohout** [comment]
Thanks for the contribution 👍

**Pull request merged**
