### PR TITLE
Improvements for using the project with Carthage

### PR DESCRIPTION
**Pull request by mpdifran**
- Add Carthage Checkouts to gitignore. This is needed in order
to allow sharing of the Swinject framework in containing
apps.
- Manually copy over configuration files into the repo. The
same thing was done for SwinjectStoryboard.

### CODE REVIEW

**Comment by mpdifran** [comment]
Can someone kick off Travis again? I think the issue is unrelated to my PR.

**Comment by jakubvano** [comment]
@mpdifran I've checked the build log, it fails with
> The command "curl -L -O https://github.com/Carthage/Carthage/releases/download/0.17.2/Carthage.pkg sudo installer -pkg Carthage.pkg -target / carthage bootstrap --no-use-binaries --no-build" failed and exited with 2

It looks like it is trying to execute 3 commands as one - I'd say that there are missing `-` on the lines in the `before_install` phase you've added.

**Comment by mpdifran** [comment]
Oops, ok, I'll look into fixing it.

**Comment by tkohout** [comment]
Thanks, looks good. The pull request is continued here: https://github.com/Swinject/SwinjectAutoregistration/pull/41

**Pull request closed without merging**
